apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: devopsfaith/krakend:2.8.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend/krakend.json
              subPath: krakend.json
      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
            items:
              - key: krakend.json
                path: krakend.json
