apiVersion: v1
kind: Service
metadata:
  name: krakend-service
  labels:
    app: krakend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: krakend
