global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
  - job_name: 'main-service'
    static_configs:
      - targets: ['main-service:8082']
