replicaCount: 1

image:
  repository: book-server
  tag: "4.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8090

resources: {}

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
