apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: default
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgresql-exporter-prometheus-postgres-exporter # Укажите правильный селектор
  ports:
    - protocol: TCP
      port: 9187        # Внешний порт
      targetPort: 9187  # Порт, на котором работает экспортер
