replicaCount: 1

image:
  repository: auth-server
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8081
  NodePort: 32040

resources: {}

serviceAccount:
  create: false


ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
