apiVersion: v1
kind: Service
metadata:
  name: graylog
spec:
  type: NodePort
  ports:
    - name: web
      port: 9000
      targetPort: 9000
      nodePort: 30090
      protocol: TCP
    - name: gelf-udp
      port: 12201
      targetPort: 12201
      nodePort: 31201
      protocol: UDP
    - name: sys-udp
      port: 514
      targetPort: 514
      protocol: UDP
  selector:
    app: graylog
